version: "3.8"

services:
  souzip-api:
    image: asia-northeast3-docker.pkg.dev/souzip-488211/souzip-dev-repo/souzip-api:latest
    container_name: souzip-api
    restart: always
    networks:
      - souzip-network
    env_file:
      - .env
    volumes:
      - /home/souzip-dev/secrets:/home/souzip-dev/secrets:ro
    ports:
      - "127.0.0.1:8080:8080"

networks:
  souzip-network:
    external: true
