spring:
  application:
    name: souzip-api
  profiles:
    default: local

server:
  port: 8080

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%X{traceId}] [%-5level] %logger{36} - %msg%n"
  level:
    root: INFO
    com.souzip.api: DEBUG

external:
  api:
    countries-base-url: https://restcountries.com/v3.1
    exchange-rate-base-url: https://v6.exchangerate-api.com/v6/6bb64d753d5d604c571e963d/latest
