spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
  prometheus:
    metrics:
      export:
        enabled: true
