spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  flyway:
    enabled: false

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins:
    - http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

