spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_POSTGRES_USER}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins:
    - http://localhost:5173
    - https://admin-dev.souzip.com
    - https://admin.souzip.com

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: classpath:logback-prod.xml
