spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_POSTGRES_USER}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins:
    - http://localhost:5173
    - https://admin-dev.souzip.com
    - https://admin.souzip.com

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when-authorized
