version: "3.8"

services:
  backend:
    image: asia-northeast3-docker.pkg.dev/souzip-488211/souzip-prod-repo/souzip-api:latest
    container_name: souzip-api-green
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - /home/souzip-prod/secrets:/home/souzip-prod/secrets:ro
      - /home/souzip-prod/logs/souzip-api:/home/souzip-prod/logs/souzip-api
    restart: always

networks:
  default:
    name: souzip-network
    external: true
