server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://souzip-loki-prod:3100/loki/api/v1/push

scrape_configs:
  - job_name: souzip-api-blue
    static_configs:
      - targets: [localhost]
        labels:
          job: souzip-api
          environment: prod
          deployment: blue
          __path__: /logs/souzip-api-blue/*.log

  - job_name: souzip-api-green
    static_configs:
      - targets: [localhost]
        labels:
          job: souzip-api
          environment: prod
          deployment: green
          __path__: /logs/souzip-api-green/*.log
