version: "3.8"

services:
  souzip-api:
    image: souzip.kr.ncr.ntruss.com/souzip/souzip-api:latest
    container_name: souzip-api
    restart: always
    networks:
      - souzip-network
    ports:
      - "8080:8080"
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: souzip-dev-db
    restart: always
    networks:
      - souzip-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: souzip_dev
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

networks:
  souzip-network:
    external: true

volumes:
  postgres-data:
    driver: local