[[auth-api]]
== Authentication API

[[auth-login]]
=== 소셜 로그인

OAuth를 통한 로그인 API입니다. 신규 사용자의 경우 자동으로 회원가입이 진행됩니다.

[[auth-login-kakao]]
==== Kakao

===== 신규 사용자
operation::auth/login-kakao-new-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

===== 기존 사용자
operation::auth/login-kakao-existing-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

===== Kakao API 에러
operation::auth/login-kakao-api-error[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


[[auth-login-google]]
==== Google

===== 신규 사용자
operation::auth/login-google-new-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

===== 기존 사용자
operation::auth/login-google-existing-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


[[auth-login-apple]]
==== Apple

===== 신규 사용자
operation::auth/login-apple-new-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

===== 기존 사용자
operation::auth/login-apple-existing-user[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


[[auth-login-errors]]
==== 로그인 에러 케이스

===== 지원하지 않는 Provider
operation::auth/login-unsupported-provider[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

===== 잘못된 Provider 형식
operation::auth/login-invalid-provider[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


[[auth-refresh]]
=== 토큰 재발급

Access Token이 만료되었을 때 Refresh Token을 사용하여 새로운 토큰을 발급받는 API입니다.

* Refresh Token 유효기간이 10일 초과 남았을 경우: Access Token만 재발급
* Refresh Token 유효기간이 10일 이하 남았을 경우: Access Token과 Refresh Token 모두 재발급

==== 정상 케이스 (Access Token만 재발급)
operation::auth/refresh-valid-token[snippets='http-request,request-fields,http-response,response-fields']

==== 만료 임박 케이스 (둘 다 재발급)
operation::auth/refresh-expiring-soon[snippets='http-request,request-fields,http-response,response-fields']

==== 에러 케이스

===== 만료된 Refresh Token
operation::auth/refresh-expired-token[snippets='http-request,request-fields,http-response,response-fields']

===== 유효하지 않은 Refresh Token
operation::auth/refresh-invalid-token[snippets='http-request,request-fields,http-response,response-fields']


[[auth-logout]]
=== 로그아웃

사용자의 Refresh Token을 삭제하여 로그아웃합니다.

* 인증 필요

operation::auth/logout[snippets='http-request,http-response,response-fields']

NOTE: 로그아웃 후에는 클라이언트에서 저장된 Access Token과 Refresh Token을 모두 삭제해야 합니다.
