[[discovery-api]]
== Discovery API

* 인증 불필요 (Public API)

[[discovery-category-top10]]
=== 카테고리별 추천 기념품 TOP 10 (New)

특정 카테고리에 속하는 추천 기념품을 조회하는 API입니다.

NOTE: 조회 결과는 최근 생성된 기념품 10개까지 제공됩니다.

operation::recommend/category-top10[snippets='http-request,path-parameters,http-response,response-fields']


[[discovery-country-top10]]
=== 나라별 추천 기념품 TOP 10 (Deprecated)

[WARNING]
====
이 API는 곧 제거될 예정입니다. 신규 API로 전환해주세요.
(해당 API는 기존 클라이언트 호환을 위해 유지 중입니다.)
====

특정 나라에서 등록된 추천 기념품을 조회하는 API입니다.

NOTE: 조회 결과는 최근 생성된 기념품 10개까지 제공됩니다.

operation::recommend/country-top10[snippets='http-request,path-parameters,http-response,response-fields']


[[discovery-top-countries-with-souvenirs]]
=== 기념품 최다등록 국가 TOP 10 + 국가별 추천 기념품 TOP 10 (New)

기념품 등록 수 기준 상위 10개 국가를 조회하고, 각 국가별 추천 기념품을 최대 10개까지 함께 제공합니다.

NOTE: 국가 목록은 기념품 등록 수(souvenirCount) 내림차순이며, 국가별 기념품 목록은 최근 생성된 기념품 최대 10개를 제공합니다.

operation::recommend/countries-top10-souvenirs-top10[snippets='http-request,http-response,response-fields']


[[discovery-top-countries-top10]]
=== 기념품 최다등록 국가 TOP 10 (Deprecated)

[WARNING]
====
이 API는 곧 제거될 예정입니다. 신규 API로 전환해주세요.
====

전체 기간 동안 등록된 기념품 수를 기준으로 가장 많은 기념품이 등록된 국가 Top 10을 조회합니다.

operation::recommend/stats-top10[snippets='http-request,http-response,response-fields']


[[discovery-top-countries-top3]]
=== 기념품 최다등록 국가 TOP 3 (Deprecated)

[WARNING]
====
이 API는 곧 제거될 예정입니다. 신규 API로 전환해주세요.
====

전체 기간 동안 등록된 기념품 수를 기준으로 가장 많은 기념품이 등록된 국가 Top 3를 조회합니다.

operation::recommend/stats-top3[snippets='http-request,http-response,response-fields']
