[[user-api]]
== User API

[[user-check-nickname]]
=== 닉네임 중복 확인

온보딩 전에 닉네임 사용 가능 여부를 확인하는 API입니다.

* 인증 필요
* 닉네임은 2~11자까지 입력 가능합니다.

==== 사용 가능한 닉네임
operation::user/check-nickname-available[snippets='http-request,request-fields,http-response,response-fields']

==== 이미 사용 중인 닉네임
operation::user/check-nickname-unavailable[snippets='http-request,request-fields,http-response,response-fields']


[[user-onboarding]]
=== 온보딩 완료

신규 사용자가 온보딩을 완료하고 약관 동의, 닉네임, 프로필 이미지 색상, 관심 카테고리를 설정하는 API입니다.

* 인증 필요
* 온보딩은 최초 1회만 가능합니다.
* 필수 약관에 모두 동의해야 합니다 (만 14세 이상, 서비스 이용약관, 개인정보 수집 및 이용, 위치기반 서비스)
* 마케팅 수신 동의는 선택 사항입니다.
* 닉네임은 2~11자까지 입력 가능하며, 한글/영문/숫자만 사용 가능합니다.
* 프로필 이미지는 색상(red, blue, yellow, purple) 중 선택합니다.
* 카테고리는 최소 1개, 최대 5개 선택이 가능합니다.

operation::user/onboarding-success[snippets='http-request,request-fields,http-response,response-fields']

NOTE: 온보딩 완료 후 재로그인 시 `needsOnboarding: false`가 반환됩니다.

[[user-onboarding-errors]]
==== 온보딩 에러 케이스

===== 필수 약관 미동의
operation::user/onboarding-required-agreement-not-checked[snippets='http-request,request-fields,http-response,response-fields']

===== 닉네임 중복
operation::user/onboarding-nickname-duplicated[snippets='http-request,request-fields,http-response,response-fields']

===== 이미 온보딩 완료
operation::user/onboarding-already-completed[snippets='http-request,request-fields,http-response,response-fields']

===== 유효하지 않은 카테고리
operation::user/onboarding-invalid-category[snippets='http-request,request-fields,http-response,response-fields']

===== 유효하지 않은 프로필 색상
operation::user/onboarding-invalid-profile-color[snippets='http-request,request-fields,http-response,response-fields']


[[user-withdraw]]
=== 회원탈퇴

사용자의 계정을 탈퇴합니다. Soft delete 방식으로 처리되며, Refresh Token과 약관 동의 정보도 함께 삭제됩니다.

* 인증 필요

operation::user/withdraw[snippets='http-request,http-response,response-fields']

NOTE: 회원탈퇴 후 동일한 OAuth 계정으로 재가입 시 새로운 사용자로 취급되며, 온보딩을 다시 진행해야 합니다.


[[user-my-page]]
=== 마이페이지

사용자의 프로필과 등록한 기념품 목록을 조회하는 API입니다.

[[user-my-profile]]
==== 내 프로필 조회

* 인증 필요

operation::user/my-profile[snippets='http-request,http-response,response-fields']


[[user-my-souvenirs]]
==== 내가 등록한 기념품 목록 조회

컬렉션 탭에 표시할 기념품 목록을 조회합니다.

* 인증 필요

operation::user/my-souvenirs[snippets='http-request,query-parameters,http-response,response-fields']

==== 페이징 예시

===== 2페이지 조회
operation::user/my-souvenirs-page-2[snippets='http-request,query-parameters,http-response,response-fields']

==== 등록한 기념품이 없는 경우
operation::user/my-souvenirs-empty[snippets='http-request,query-parameters,http-response,response-fields']

NOTE: 기념품 목록은 생성일시 기준 내림차순으로 정렬됩니다. 찜 탭 기능은 추후 구현 예정입니다.
