[[admin-api]]
== Admin API

[[admin-login]]
=== 어드민 로그인

어드민 계정으로 로그인합니다.

operation::admin/login[snippets='http-request,request-fields,http-response,response-fields']

[[admin-refresh]]
=== 어드민 토큰 갱신

Refresh Token을 사용하여 새로운 Access Token을 발급받습니다.

==== 유효한 토큰

Refresh Token의 유효기간이 10일 초과 남은 경우, Access Token만 재발급됩니다.

operation::admin/refresh-valid-token[snippets='http-request,request-fields,http-response,response-fields']

==== 만료 임박 토큰

Refresh Token의 유효기간이 10일 이하로 남은 경우, Access Token과 Refresh Token이 모두 재발급됩니다.

operation::admin/refresh-expiring-soon[snippets='http-request,request-fields,http-response,response-fields']

==== 만료된 토큰

operation::admin/refresh-expired-token[snippets='http-request,request-fields,http-response,response-fields']

==== 유효하지 않은 토큰

operation::admin/refresh-invalid-token[snippets='http-request,request-fields,http-response,response-fields']

[[admin-logout]]
=== 어드민 로그아웃

어드민 계정을 로그아웃하고 Refresh Token을 삭제합니다.

* Authorization 헤더에 Access Token이 필요합니다.

operation::admin/logout[snippets='http-request,request-headers,http-response,response-fields']

[[admin-management]]
=== 관리자 관리

[[admin-invite]]
==== 관리자 초대

새로운 관리자를 초대합니다.

* SUPER_ADMIN 권한이 필요합니다.
* ADMIN 또는 VIEWER 역할만 초대 가능합니다.
* SUPER_ADMIN 역할은 초대할 수 없습니다.

operation::admin/invite-admin[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[admin-list]]
==== 관리자 목록 조회

관리자 목록을 페이징하여 조회합니다.

* SUPER_ADMIN 권한이 필요합니다.
* SUPER_ADMIN 역할은 목록에 표시되지 않습니다.
* 페이지 번호는 1부터 시작합니다.
* 기본 페이지 크기는 10이며, 최대 30까지 가능합니다.

operation::admin/get-admins[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[admin-delete]]
==== 관리자 삭제

관리자를 삭제합니다.

* SUPER_ADMIN 권한이 필요합니다.

operation::admin/delete-admin[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[country-list]]
==== 나라 목록 조회

나라 목록을 조회합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.

operation::admin/get-countries[snippets='http-request,request-headers,http-response,response-fields']

[[city-list]]
==== 도시 목록 조회

나라별 도시 목록을 조회합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.
* countryId는 필수 파라미터입니다.
* 우선순위 오름차순, 우선순위 없는 도시는 이름 오름차순으로 정렬됩니다.

operation::admin/get-cities[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[city-priority]]
==== 도시 우선순위 설정

도시의 검색 우선순위를 설정합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.
* priority 미입력 시 우선순위가 초기화됩니다.
* 우선순위는 1 이상이어야 합니다.
* 같은 국가 내에서 우선순위가 중복되지 않도록 자동으로 조정됩니다.

operation::admin/update-city-priority[snippets='http-request,request-headers,path-parameters,query-parameters,http-response,response-fields']

[[city-priority-reset]]
==== 도시 우선순위 초기화

도시의 검색 우선순위를 초기화합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.

operation::admin/reset-city-priority[snippets='http-request,request-headers,path-parameters,http-response,response-fields']
