[[admin-api]]
== Admin API

[[admin-login]]
=== 어드민 로그인

어드민 계정으로 로그인합니다.

operation::admin/login[snippets='http-request,request-fields,http-response,response-fields']

[[admin-refresh]]
=== 어드민 토큰 갱신

Refresh Token을 사용하여 새로운 Access Token을 발급받습니다.

==== 유효한 토큰

Refresh Token의 유효기간이 10일 초과 남은 경우, Access Token만 재발급됩니다.

operation::admin/refresh-valid-token[snippets='http-request,request-fields,http-response,response-fields']

==== 만료 임박 토큰

Refresh Token의 유효기간이 10일 이하로 남은 경우, Access Token과 Refresh Token이 모두 재발급됩니다.

operation::admin/refresh-expiring-soon[snippets='http-request,request-fields,http-response,response-fields']

==== 만료된 토큰

operation::admin/refresh-expired-token[snippets='http-request,request-fields,http-response,response-fields']

==== 유효하지 않은 토큰

operation::admin/refresh-invalid-token[snippets='http-request,request-fields,http-response,response-fields']

[[admin-logout]]
=== 어드민 로그아웃

어드민 계정을 로그아웃하고 Refresh Token을 삭제합니다.

* Authorization 헤더에 Access Token이 필요합니다.

operation::admin/logout[snippets='http-request,request-headers,http-response,response-fields']

[[admin-management]]
=== 관리자 관리

[[admin-invite]]
==== 관리자 초대

새로운 관리자를 초대합니다.

* SUPER_ADMIN 권한이 필요합니다.
* ADMIN 또는 VIEWER 역할만 초대 가능합니다.
* SUPER_ADMIN 역할은 초대할 수 없습니다.

===== ADMIN 역할 초대

operation::admin/invite-admin[snippets='http-request,request-headers,request-fields,http-response,response-fields']

===== VIEWER 역할 초대

operation::admin/invite-viewer[snippets='http-request,request-headers,request-fields,http-response,response-fields']

===== SUPER_ADMIN 초대 시도 (실패)

operation::admin/invite-super-admin-fails[snippets='http-request,request-fields,http-response,response-fields']

===== 중복된 아이디로 초대 (실패)

operation::admin/invite-duplicate-username[snippets='http-request,request-fields,http-response,response-fields']
