[[admin-location]]
== 지역 관리

[[country-list]]
=== 나라 목록 조회

나라 목록을 조회합니다.

* SUPER_ADMIN 또는 ADMIN 또는 VIEWER 권한이 필요합니다.

operation::admin/get-countries[snippets='http-request,request-headers,http-response,response-fields']

[[city-list]]
=== 도시 목록 조회

나라별 도시 목록을 페이징하여 조회합니다.

* SUPER_ADMIN 또는 ADMIN 또는 VIEWER 권한이 필요합니다.
* keyword 입력 시 한글명, 영문명으로 검색됩니다.
* 우선순위 오름차순, 우선순위 없는 도시는 이름 오름차순으로 정렬됩니다.
* 페이지 번호는 1부터 시작합니다.
* 기본 페이지 크기는 10이며, 최대 30까지 가능합니다.

operation::admin/get-cities[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[city-create]]
=== 도시 추가

도시를 추가합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.

operation::admin/create-city[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[city-delete]]
=== 도시 삭제

도시를 삭제합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.

operation::admin/delete-city[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[city-priority]]
=== 도시 우선순위 설정

도시의 검색 우선순위를 설정합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.
* priority 미입력 시 우선순위가 초기화됩니다.
* 우선순위는 1 이상이어야 합니다.
* 같은 국가 내에서 우선순위가 중복되지 않도록 자동으로 조정됩니다.

operation::admin/update-city-priority[snippets='http-request,request-headers,path-parameters,query-parameters,http-response,response-fields']

[[city-priority-reset]]
=== 도시 우선순위 초기화

도시의 검색 우선순위를 초기화합니다.

* SUPER_ADMIN 또는 ADMIN 권한이 필요합니다.

operation::admin/reset-city-priority[snippets='http-request,request-headers,path-parameters,http-response,response-fields']
