--
-- PostgreSQL database dump
--


-- Dumped from database version 14.18
-- Dumped by pg_dump version 15.15 (Homebrew)


--
-- Name: cdb_admin; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA IF NOT EXISTS cdb_admin;


-- ALTER SCHEMA cdb_admin OWNER TO postgres;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


-- ALTER SCHEMA public OWNER TO postgres;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

-- CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA cdb_admin;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';




--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action character varying(255) NOT NULL,
    app_version character varying(255),
    category character varying(255) NOT NULL,
    device_type character varying(255),
    failure_reason character varying(255),
    ip_address character varying(255) NOT NULL,
    metadata text,
    provider character varying(255),
    success boolean NOT NULL,
    target_id bigint,
    target_type character varying(255),
    user_agent text,
    user_id character varying(255)
);


ALTER TABLE public.audit_log OWNER TO souzip_admin;

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: city; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.city (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    latitude numeric(38,2) NOT NULL,
    longitude numeric(38,2) NOT NULL,
    name_en character varying(255) NOT NULL,
    name_kr character varying(255) NOT NULL,
    country_id bigint
);


ALTER TABLE public.city OWNER TO souzip_admin;

--
-- Name: city_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.country (
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    created_at timestamp(6) without time zone,
    currency_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    capital character varying(255),
    code character varying(255) NOT NULL,
    image_url character varying(255) NOT NULL,
    name_en character varying(255) NOT NULL,
    name_kr character varying(255) NOT NULL,
    region character varying(255) NOT NULL
);


ALTER TABLE public.country OWNER TO souzip_admin;

--
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.currency (
    id bigint NOT NULL,
    code character varying(10) NOT NULL,
    symbol character varying(10)
);


ALTER TABLE public.currency OWNER TO souzip_admin;

--
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchange_rate; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.exchange_rate (
    rate numeric(20,6) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    base_code character varying(255) NOT NULL,
    currency_code character varying(255) NOT NULL
);


ALTER TABLE public.exchange_rate OWNER TO souzip_admin;

--
-- Name: exchange_rate_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.exchange_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.file (
    display_order integer NOT NULL,
    created_at timestamp(6) without time zone,
    entity_id bigint NOT NULL,
    file_size bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    entity_type character varying(255) NOT NULL,
    original_name character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    souvenir_id bigint
);


ALTER TABLE public.file OWNER TO souzip_admin;

--
-- Name: file_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.refresh_token (
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    token character varying(255) NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO souzip_admin;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: souvenir; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.souvenir (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    country_code character varying(255),
    currency_symbol character varying(10),
    deleted boolean NOT NULL,
    description character varying(1000),
    is_owned boolean NOT NULL,
    krw_price integer,
    latitude numeric(10,7) NOT NULL,
    local_price integer,
    location_detail character varying(255),
    longitude numeric(10,7) NOT NULL,
    name character varying(30) NOT NULL,
    purpose character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.souvenir OWNER TO souzip_admin;

--
-- Name: souvenir_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.souvenir ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.souvenir_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) without time zone,
    email character varying(255),
    name character varying(100) NOT NULL,
    nickname character varying(100),
    profile_image_url character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    restored_at timestamp(6) without time zone,
    user_id character varying(36) NOT NULL,
    onboarding_completed boolean DEFAULT false NOT NULL
);


ALTER TABLE public."user" OWNER TO souzip_admin;

--
-- Name: user_agreement; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.user_agreement (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age_verified boolean NOT NULL,
    location_service boolean NOT NULL,
    marketing_consent boolean NOT NULL,
    privacy_required boolean NOT NULL,
    service_terms boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_agreement OWNER TO souzip_admin;

--
-- Name: user_agreement_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public.user_agreement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_category; Type: TABLE; Schema: public; Owner: souzip_admin
--

CREATE TABLE public.user_category (
    user_id bigint NOT NULL,
    category character varying(255)
);


ALTER TABLE public.user_category OWNER TO souzip_admin;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: souzip_admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: cdb_admin; Owner: postgres
--



--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: city; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: exchange_rate; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: file; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: souvenir; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: user_agreement; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Data for Name: user_category; Type: TABLE DATA; Schema: public; Owner: souzip_admin
--



--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: city_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: exchange_rate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: souvenir_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: user_agreement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: souzip_admin
--



--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: city city_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT city_pkey PRIMARY KEY (id);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- Name: currency currency_code_key; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_code_key UNIQUE (code);


--
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- Name: exchange_rate exchange_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.exchange_rate
    ADD CONSTRAINT exchange_rate_pkey PRIMARY KEY (id);


--
-- Name: file file_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_token_key; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_key UNIQUE (token);


--
-- Name: souvenir souvenir_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.souvenir
    ADD CONSTRAINT souvenir_pkey PRIMARY KEY (id);


--
-- Name: user uk6icoy2m5c9xvcuer66s7kkjv6; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT uk6icoy2m5c9xvcuer66s7kkjv6 UNIQUE (user_id);


--
-- Name: user ukavppunt4c0qpxo9giv18an98o; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT ukavppunt4c0qpxo9giv18an98o UNIQUE (provider, provider_id);


--
-- Name: file uq_file_entity_order; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT uq_file_entity_order UNIQUE (entity_type, entity_id, display_order);


--
-- Name: user_agreement user_agreement_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.user_agreement
    ADD CONSTRAINT user_agreement_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_action; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_audit_action ON public.audit_log USING btree (action, created_at);


--
-- Name: idx_audit_category; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_audit_category ON public.audit_log USING btree (category, created_at);


--
-- Name: idx_audit_created_at; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_audit_created_at ON public.audit_log USING btree (created_at DESC);


--
-- Name: idx_audit_target; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_audit_target ON public.audit_log USING btree (target_type, target_id);


--
-- Name: idx_audit_user_id; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_audit_user_id ON public.audit_log USING btree (user_id);


--
-- Name: idx_city_country; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_city_country ON public.city USING btree (country_id);


--
-- Name: idx_city_name; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_city_name ON public.city USING btree (name_en, name_kr);


--
-- Name: idx_deleted; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_deleted ON public."user" USING btree (deleted);


--
-- Name: idx_email; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_email ON public."user" USING btree (email);


--
-- Name: idx_file_created_at; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_file_created_at ON public.file USING btree (created_at);


--
-- Name: idx_file_entity; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_file_entity ON public.file USING btree (entity_type, entity_id);


--
-- Name: idx_file_entity_order; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_file_entity_order ON public.file USING btree (entity_type, entity_id, display_order);


--
-- Name: idx_file_storage_key; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_file_storage_key ON public.file USING btree (storage_key);


--
-- Name: idx_provider; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_provider ON public."user" USING btree (provider, provider_id);


--
-- Name: idx_refresh_token_token; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_refresh_token_token ON public.refresh_token USING btree (token);


--
-- Name: idx_refresh_token_user_id; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_refresh_token_user_id ON public.refresh_token USING btree (user_id);


--
-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: souzip_admin
--

CREATE INDEX idx_user_id ON public."user" USING btree (user_id);


--
-- Name: user_category fk6gbxowf7xyes5y6gqf7qu7haf; Type: FK CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.user_category
    ADD CONSTRAINT fk6gbxowf7xyes5y6gqf7qu7haf FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: souvenir fkforav2lab0pssqkonqt34m5f9; Type: FK CONSTRAINT; Schema: public; Owner: souzip_admin
--

ALTER TABLE ONLY public.souvenir
    ADD CONSTRAINT fkforav2lab0pssqkonqt34m5f9 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: SCHEMA cdb_admin; Type: ACL; Schema: -; Owner: postgres
--



--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--



--
-- Name: TABLE geography_columns; Type: ACL; Schema: cdb_admin; Owner: postgres
--



--
-- Name: TABLE geometry_columns; Type: ACL; Schema: cdb_admin; Owner: postgres
--



--
-- Name: TABLE spatial_ref_sys; Type: ACL; Schema: cdb_admin; Owner: postgres
--



--
-- PostgreSQL database dump complete
--
