name: souzip CI/CD

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test -x asciidoctor

      - name: NCP Container Registry Login
        run: |
          echo ${{ secrets.NCP_SECRET_KEY }} | docker login souzip.kr.ncr.ntruss.com -u ${{ secrets.NCP_ACCESS_KEY }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t souzip.kr.ncr.ntruss.com/souzip/souzip-api:${GITHUB_SHA} .

      - name: Push Docker Image
        run: |
          docker push souzip.kr.ncr.ntruss.com/souzip/souzip-api:${GITHUB_SHA}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NCP_SERVER_HOST}}
          username: ${{ secrets.NCP_SERVER_USER }}
          key: ${{ secrets.NCP_SERVER_SSH_KEY }}
          script: |
            docker login souzip.kr.ncr.ntruss.com -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
            
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      
            cd souzip-api/docker
            docker-compose pull
            docker-compose down
            docker-compose up -d